name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Distribution
        run: |
          mkdir -p dist
          cp src/favicon.ico src/index.js src/style.css src/index.html -t dist/
          cd HTMLMinifier
          npm install
          npm run build
          cp dist/htmlminifier.umd.bundle.min.js ../dist/hm.js
          HVER=$(node -p "require('./package.json').version")
          sed -i "s/{HMT_VERSION}/$HVER/g" ../dsit/index.html
          TVER=$(npm list terser --depth=0 | grep ' terser@' | awk -F@ '{ print $2 }')
          sed -i "s/{TERSER_VERSION}/$TVER/g" ../dsit/index.html
          CVER=$(npm list clean-css --depth=0 | grep ' clean-css@' | awk -F@ '{ print $2 }')
          sed -i "s/{CCSS_VERSION}/$CVER/g" ../dsit/index.html
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: hm.ehhh.eu.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
